### ISSUE TITLE
CSS Autocomplete with ":"

### ISSUE THREAD

**Issue by russellgreenwood** [atom/autocomplete-plus#103]
Not sure if it's me doing something wrong, but it would seem sensible that autocompletion on CSS/SCSS would automatically insert the ":" when you select the suggestion - which this doesn't seem to currently do. 

Is this to do with Autocomplete-plus, or the CSS/SCSS language packs?

**Comment by michaelott-stormbox** [comment]
+1 for this little addition please, with CSS, SCSS and LESS support would be nice.

**Comment by mikeott** [comment]
+1 for this little addition please, with CSS, SCSS and LESS support would be nice. It is a curious and unexpected omission.

**Comment by joefitzgerald** [comment]
@mikeott, this would be best addressed in CSS / SCSS / LESS autocomplete-plus providers. It is not something that will be part of the core autocomplete-plus package. /cc @benogle, who is thinking of working on one or more of these.

**Comment by joefitzgerald** [comment]
See also: https://github.com/atom-community/autocomplete-plus/wiki/Autocomplete-Providers and https://github.com/atom-community/autocomplete-plus/wiki/Provider-API.

**Comment by mikeott** [comment]
Thanks @joefitzgerald - I'm new to Atom, still getting used to things.

**Comment by benogle** [comment]
Yeah a less/CSS provider is on my list.

**Comment by fredericlefeurmou** [comment]
+1
