### ISSUE TITLE
Crashes Atom when used with pigments

### ISSUE THREAD

**Issue by ProLoser** [atom/autocomplete-plus#429]
When used with `pigments` only, simply writing a few characters in a `scss` file causes the entire editor to crash.

See https://github.com/abe33/atom-pigments/issues/7

**Comment by benogle** [comment]
@abe33 is this still an issue?

**Comment by mnquintana** [comment]
I haven't ever managed to reproduce this, and I've been using pigments in SCSS files for a long time now.

**Comment by benogle** [comment]
Rad, closing.

**Comment by abe33** [comment]
It should have been fixed for some time now, it was due to the way I was evaluating the variables found in a project as a color when building the autocomplete array. Now I use a collection that manage that in a more granular way so that we don't have to evaluate variables except when they or on their dependencies is modified.

**Comment by simpsondigital** [comment]
Think there is still an issue with Pigments. Crashing Atom hard for me. I've narrowed it down to that plugin, and every time I re-enable it, Atom becomes entirely unresponsive. Running OS X 10.10.5.

**Comment by lee-dohm** [comment]
@simpsondigital You should probably open an Issue on the [pigments package](https://atom.io/packages/pigments) if there isn't one already.

**Comment by simpsondigital** [comment]
I did indeed, thanks for the reply.
