### ISSUE TITLE
Autocomplete not working for .css files

### ISSUE THREAD

**Issue by tplyons92** [atom/autocomplete-plus#757]
When I am editing a .css file, suggestion or autocomplete of a tag is not happening.

**Comment by 50Wliu** [comment]
@tplyons92 Can you reproduce this in safe mode (`atom  --safe`)?  In addition, what Atom version and OS are you using?

**Comment by FXDuke** [comment]
I have the same problem (and in safe mode) just when slit screen and .css file is on the right side. OS: Windows 7 x64. Atom version: 1.9.9.

**Comment by 50Wliu** [comment]
@FXDuke Your issue has been fixed and will be out in Atom 1.10.0, which will be released shortly.

**Comment by tobiasger** [comment]
I'm still experiencing this problem with 1.11.0. on Mac OS X El Capitan 10.11.6.

**Comment by Ben3eeE** [comment]
@tobiasger Do you see this problem in safe mode `atom --safe`? Can you provide any steps to reproduce?

**Comment by tobiasger** [comment]
@Ben3eeE Sorry, I didn't thought of this, but the problem seems to be connected with writing in SCSS. I tried to create a new document in CSS and the auto-completion worked. But when I write in a SCSS document, the auto-completion is not working.

**Comment by xxsnakerxx** [comment]
I have the same problem (with safe flag works fine!) 

Also I have tried to disable all community plugins but have no luck

Atom 1.11.2
MacOS Sierra

**Comment by Ben3eeE** [comment]
@tobiasger If you can still reproduce this problem in safe mode `atom --safe` then please open a new issue on the [autocomplete-css](https://github.com/atom/autocomplete-css/) repository. Please also follow read and follow the instructions in the [reporting bugs section](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#reporting-bugs) before doing so.

@xxsnakerxx If it works in safe mode then that indicates that it is a problem with one of your installed community packages. You might have to restart Atom after disabling the packages because they might not deactivate properly.

Closing because @tplyons92 has not provided more information to help us diagnose the problem.

**Comment by chrisallenmoore** [comment]
FYI, I just had this issue, it was caused by another atom package:
https://github.com/azat-io/atom-language-postcss/issues/2
