### ISSUE TITLE
Subsequence provider always matches input prefix before completion when matched in parentheses.

### ISSUE THREAD

**Issue by phyllisstein** [atom/autocomplete-plus#908]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
Got a kind of a weird one! With the new Subsequence provider enabled, `autocomplete-plus` returns the completion prefix as the first matching completion even when there is a "better" match in the buffer---but only when the match is being made inside parens. It's a little hard to explain, but here's a screenshot:

<img width="859" alt="screenshot" src="https://user-images.githubusercontent.com/2207980/31863237-07f2590c-b719-11e7-802e-fd57cec1ca8f.png">

When the cursor is followed by a closing parenthesis, the matches that come up are identical to what I'm typing, even though I would expect `currentBuild` to be the first result.

### Steps to Reproduce

1. Type parentheses into a buffer.
2. Move the cursor inside the parentheses.
3. Try to complete a nearby word.
4. 💥 

**Expected behavior:** The nearby word should be the first match returned.

**Actual behavior:** The prefix is the first match returned.

**Reproduces how often:** 100% of the time.

### Versions
```
~ ❯❯❯ atom --version
Atom    : 1.22.0-beta1
Electron: 1.6.15
Chrome  : 56.0.2924.87
Node    : 7.4.0

~ ❯❯❯ apm --version
apm  1.18.8
npm  3.10.10
node 6.9.5 x64
python 2.7.10
git 2.14.2

~ ❯❯❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13
BuildVersion:	17A362a
```

### Additional Information
❤️

**Comment by leroix** [comment]
Hi @phyllisstein, thanks for the note!

I'm fairly certain this should be fixed when the next beta gets released. This was one of the things I addressed in https://github.com/atom/autocomplete-plus/pull/906.

**Comment by phyllisstein** [comment]
Oh neat! Sorry I didn't catch that when I did my Issues search. I'm afraid I'm still having some trouble after installing from a fork rebased on `master`, though:

![screenflow](https://user-images.githubusercontent.com/2207980/31872507-7e1cfcb0-b78a-11e7-891c-b0f78f029e5c.gif)

I'd normally say that maybe Atom is still using the built-in module but it has other changes from the fork so I think there may still be a glitch.

**Comment by leroix** [comment]
![autocomplete](https://user-images.githubusercontent.com/520209/31909428-516ece74-b7f7-11e7-9904-4a9d4ab7dfe0.gif)

I'm unable to reproduce unfortunately. Could you verify that you're using the "Subsequence" provider? Also, could you verify that your build is using the latest autocomplete-plus release?

**Comment by phyllisstein** [comment]
Right you are! I built Atom from `master` and it worked fine---I guess the old core package _was_ still being used. Thanks so much for pointing me in the right direction, and for this work!
